@baseUrl = http://localhost:8080
@userId = 5af2e83f6dd9dd1834f50131

@token = putTokenHere

###

GET {{baseUrl}}/users
x-access-token: {{token}}

###

GET {{baseUrl}}/users/{{userId}}
x-access-token: {{token}}

###

POST {{baseUrl}}/users
content-type: application/json
x-access-token: {{token}}

{
  "user": {
    "name": "tester",
    "email": "tester1@gmail.com",
    "password": "helloWorld"
  }
}

###

PUT {{baseUrl}}/users/{{userId}}
content-type: application/json
x-access-token: {{token}}

{
  "user": {
    "name": "tester8"
  }
}

###

DELETE {{baseUrl}}/users/{{userId}}
x-access-token: {{token}}